# Configuration paths for CHAIR Benchmark on Qwen2-VL
coco_val2014_images: "/home/nvidia-lab/ai4life/phuongnh/vlm-truth/data/coco2014/val2014"
chair_manifest: "benchmarks/chair/selected_chair_val2014_seed2027.json"
chair_eval_cache: "benchmarks/chair/chair.pkl"
chair_annotation_dir: "/home/nvidia-lab/ai4life/phuongnh/vlm-truth/data/coco2014/captions/annotations"
chair_annotation_file: "/home/nvidia-lab/ai4life/phuongnh/vlm-truth/data/coco2014/captions/annotations/instances_val2014.json"
chair_caption_file: "/home/nvidia-lab/ai4life/phuongnh/vlm-truth/data/coco2014/captions/annotations/captions_val2014.json"

models:
  qwen2vl_7b_instruct_ckpt: "Qwen/Qwen2-VL-7B-Instruct"
